services:
  sdp:
    platform: linux/amd64
    image: libera-utils:latest
    build:
      context: .
      target: libera-utils

  # Tests against the default version of python in the Dockerfile
  tests:
    platform: linux/amd64
    image: libera-utils-test:latest
    build:
      context: .
      target: libera-utils-test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Tests against Python 3.11 (EOL 2027-10)
  3.11-tests:
    platform: linux/amd64
    image: libera-utils-test:latest
    build:
      context: .
      target: libera-utils-test
      args:
        - BASE_IMAGE_PYTHON_VERSION=3.11
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  linting:
    platform: linux/amd64
    image: libera-utils-test:latest
    build:
      context: .
      target: libera-utils-test
    entrypoint: ["ruff", "check"]

  pypi-publish:
    platform: linux/amd64
    image: libera-utils-test:latest
    environment:
      - PYPI_TOKEN
    build:
      context: .
      target: libera-utils-test
    entrypoint:
      [
        "poetry",
        "publish",
        "--build",
        "--username",
        "__token__",
        "--password",
        "${PYPI_TOKEN}",
      ]
