version: '3.8'

services:
  libera-dev-db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=libera_master
      - POSTGRES_PASSWORD=masterpass
      - POSTGRES_DB=postgres
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d

  flyway-sdp-dev:
    image: flyway/flyway:latest
    environment:
      - FLYWAY_PASSWORD=masterpass
      - FLYWAY_CONNECT_RETRIES=60
    command: -url=jdbc:postgresql://libera-dev-db:5432/sdp_dev migrate
    volumes:
      - ./database/migrations:/flyway/sql
      - ./database/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      - libera-dev-db

  flyway-sdp-test:
    image: flyway/flyway:latest
    environment:
      - FLYWAY_PASSWORD=masterpass
      - FLYWAY_CONNECT_RETRIES=60
    command: -url=jdbc:postgresql://libera-dev-db:5432/sdp_test migrate
    volumes:
      - ./database/migrations:/flyway/sql
      - ./database/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      - libera-dev-db

  flyway-sdp-prod:
    image: flyway/flyway:latest
    environment:
      - FLYWAY_PASSWORD=masterpass
      - FLYWAY_CONNECT_RETRIES=60
    command: -url=jdbc:postgresql://libera-dev-db:5432/sdp_prod migrate
    volumes:
      - ./database/migrations:/flyway/sql
      - ./database/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      - libera-dev-db

  sdp:
    image: libera-utils:latest
    build:
      context: .
      target: libera-utils

  tests:
    image: libera-utils-test:latest
    build:
      context: .
      target: libera-utils-test
    environment:
      - LIBERA_DB_HOST=libera-dev-db
    depends_on:
      flyway-sdp-test:
        condition: service_completed_successfully

  docs-confluence:
    image: libera-utils-docs:latest
    build:
      context: .
      target: libera-utils-docs
    command: ["confluence"]

  docs-html:
    image: libera-utils-docs:latest
    build:
      context: .
      target: libera-utils-docs
    command: [ "clean", "html" ]

  linting:
    image: libera-utils-test:latest
    build:
      context: .
      target: libera-utils-test
    entrypoint: ["pylint", "libera_utils"]

  ast:
    image: libera-utils-test:latest
    build:
      context: .
      target: libera-utils-test
    entrypoint: [ "bandit", "-r", "libera_utils" ]