"""Geolocation from the frozen dynamic kernels.

These tests consume the committed kernels in ``tests/test_data/dynamic_kernels`` rather than
building their own, mirroring production: the L1B container is handed kernels from S3 and
never generates them. Kernel *generation* is covered separately by the kernel-maker tests.

The fixture is regenerated by ``tests/fixture_generation/generate_dynamic_kernels.py`` from
the Jake Fernandez CSVs under ``tests/test_data/tier1_geo``, and covers a 60 s window centred
on closest approach to the Libya-4 calibration site during a simulated JPSS-4 overpass.

Assertion strategy: the mechanism-CK checks are exact, because the property they pin (the CKs
rotate about the *measured* axes of rotation and carry the encoder correction) is a discrete
right-or-wrong fact that regressed silently for eight months. The geolocation check is
deliberately loose, because near the limb the ground intersection is extremely sensitive to
sub-arcminute pointing changes and any tight footprint bound would be fragile across
platforms. Precision belongs at the step level, tolerance at the end-to-end level.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import pytest
from curryer import spicetime
from curryer import spicierpy as sp
from curryer.compute import constants, spatial

pytestmark = pytest.mark.integration

#: Libya-4 pseudo-invariant calibration site.
LIBYA4_LAT_DEG = 28.55
LIBYA4_LON_DEG = 23.39

#: Coverage of the frozen mechanism CKs. Must match the generation script.
FIXTURE_START = "2028-01-02 00:21:02"
FIXTURE_END = "2028-01-02 00:22:02"

#: Ideal, misalignment-free mechanism axes. The measured axes in the frame kernel are small
#: perturbations of these; the fixture must rotate about the measured ones.
NOMINAL_AZ_AXIS = np.array([0.0, 0.0, 1.0])
NOMINAL_EL_AXIS = np.array([1.0, 0.0, 0.0])


@pytest.fixture
def frozen_kernel_manager(generic_kernel_dir, isolated_kernel_cache, test_data_path):
    """A KernelManager with the committed dynamic kernels furnished, as libera_rad does it."""
    from libera_utils.libera_spice.kernel_manager import KernelManager

    kernel_dir = test_data_path / "dynamic_kernels"
    kernel_paths = sorted(f for f in kernel_dir.iterdir() if f.is_file())
    assert kernel_paths, f"No frozen kernels in {kernel_dir}"

    km = KernelManager()
    km.load_libera_dynamic_kernels(kernel_paths, needs_naif_kernels=True, needs_static_kernels=True)
    return km


def _fixed_axis_residual(rotation: np.ndarray, axis: np.ndarray) -> float:
    """How far ``axis`` moves under ``rotation``. Zero exactly when it is the rotation axis."""
    axis = axis / np.linalg.norm(axis)
    return float(np.linalg.norm(rotation @ axis - axis))


def _largest_rotation(frames: list[np.ndarray]) -> np.ndarray:
    """The rotation matrix turning through the largest angle, where the axis is best resolved."""
    return max(frames, key=lambda r: np.arccos(np.clip((np.trace(r) - 1.0) / 2.0, -1.0, 1.0)))


@pytest.mark.parametrize(
    ("from_frame", "to_frame", "axis_keyword", "nominal_axis"),
    [
        ("LIBERA_AZ_COORD", "LIBERA_BASE_COORD", "LIBERA_AZ_AOR_IN_STAND", NOMINAL_AZ_AXIS),
        ("LIBERA_EL_COORD", "LIBERA_AZ_COORD", "LIBERA_EL_AOR_IN_STAND", NOMINAL_EL_AXIS),
    ],
    ids=["azimuth", "elevation"],
)
def test_frozen_mechanism_cks_rotate_about_measured_axes(
    frozen_kernel_manager, from_frame, to_frame, axis_keyword, nominal_axis
):
    """Each frozen mechanism CK rotates about the frame kernel's measured axis, not the nominal one.

    Regression guard for the defect these fixtures carried between 2026-01 and this change: the
    committed CKs rotated about the ideal coordinate axes and omitted the encoder correction,
    having been generated before LIBSDC-668 and LIBSDC-806. Paired with the current frame
    kernel, which declares the measured axes and a misaligned radiometer boresight, that is a
    configuration no real instrument has.

    A rotation fixes its own axis, so ``R @ axis == axis`` identifies the axis directly and does
    not depend on knowing the commanded angle. Asserting the nominal axis is *not* fixed is what
    fails if the fixture is ever regenerated from a nominal-geometry path.
    """
    times = pd.date_range(FIXTURE_START, FIXTURE_END, freq="500ms", inclusive="left")
    ephemeris_times = spicetime.adapt(times, "dt64", "et")

    measured_axis = np.array(sp.gdpool(axis_keyword, 0, 3))
    rotations = [sp.pxform(from_frame, to_frame, et) for et in ephemeris_times]
    rotation = _largest_rotation(rotations)

    # The measured axis is fixed by the rotation: this is the axis the CK was built about.
    assert _fixed_axis_residual(rotation, measured_axis) < 1e-6, f"{from_frame} CK does not rotate about {axis_keyword}"

    # The nominal axis is not. The separation is the misalignment, so the threshold only has to
    # exceed CK round-trip noise while staying well under the ~0.065-0.283 deg axis tilt.
    assert _fixed_axis_residual(rotation, nominal_axis) > 1e-4, (
        f"{from_frame} CK rotates about the nominal axis -- the measured misalignment is missing"
    )


def test_frozen_azimuth_ck_reproduces_commanded_pointing(frozen_kernel_manager, test_data_path):
    """The azimuth CK encodes the commanded azimuth from the source CSV, post encoder correction.

    Ties the fixture to the data it was generated from. The generation script pre-applies the
    inverse encoder correction so that ``create_kernel_from_l1a``'s forward correction returns
    the commanded angle, and the round trip is exact, so any drift here means the fixture and
    its source have diverged.
    """
    from libera_utils import kernel_maker

    commanded = pd.read_csv(test_data_path / "tier1_geo" / "Libya-4_access003.csv", index_col=0)
    timetags = pd.to_datetime(commanded.index.values)
    in_window = (timetags >= pd.Timestamp(FIXTURE_START)) & (timetags <= pd.Timestamp(FIXTURE_END))
    timetags = timetags[in_window]
    expected_az = np.deg2rad(commanded["Command Azimuth (deg)"].to_numpy()[in_window])

    az_axis = np.array(sp.gdpool("LIBERA_AZ_AOR_IN_STAND", 0, 3))
    az_axis = az_axis / np.linalg.norm(az_axis)

    recovered = []
    for et in spicetime.adapt(timetags, "dt64", "et"):
        rotation = sp.pxform("LIBERA_AZ_COORD", "LIBERA_BASE_COORD", et)
        vee = 0.5 * np.array(
            [
                rotation[2, 1] - rotation[1, 2],
                rotation[0, 2] - rotation[2, 0],
                rotation[1, 0] - rotation[0, 1],
            ]
        )
        recovered.append(np.arctan2(vee @ az_axis, 0.5 * (np.trace(rotation) - 1.0)))

    # Tolerance covers msopck's quaternion quantisation only; the correction round trip itself
    # is exact to machine precision (see TestEncoderCorrection in tests/unit/test_kernel_maker.py).
    np.testing.assert_allclose(np.array(recovered), expected_az, atol=1e-6)
    assert kernel_maker.AZ_ENCODER_FIELD  # guards against the field being renamed out from under us


def test_frozen_spacecraft_spk_matches_the_reference_ground_track(frozen_kernel_manager, test_data_path):
    """The spacecraft SPK reproduces the reference sub-satellite ground track.

    A per-step golden check on the ephemeris alone, independent of any pointing: the SPK is built
    from ``JPSS-4_Fixed_Ephemeris_And_Attitude.csv`` (Cartesian state), and this compares it
    against ``JPSS-4_Geodetic_LLA_libya4_access03.csv`` -- the geodetic sub-satellite track for
    the same scenario, which was supplied alongside it and had never been used by a test.

    Isolating the ephemeris matters because every pointing test inherits it: a spacecraft state
    error would otherwise surface as a confusing pointing failure.
    """
    truth = pd.read_csv(test_data_path / "tier1_geo" / "JPSS-4_Geodetic_LLA_libya4_access03.csv")
    timestamps = pd.to_datetime(truth["Time (UTCG)"], format="%d %b %Y %H:%M:%S.%f")

    equatorial_radius, _, polar_radius = sp.bodvrd("EARTH", "RADII", 3)[1]
    flattening = (equatorial_radius - polar_radius) / equatorial_radius

    # Every 120th row: the track is smooth at 1 Hz, so 16 samples across the span exercise the
    # whole orbit arc without 1801 SPICE calls.
    sampled = slice(0, len(truth), 120)
    latitude_error = []
    longitude_error = []
    altitude_error = []
    for timestamp, ref_lat, ref_lon, ref_alt in zip(
        timestamps[sampled],
        truth["Lat (deg)"][sampled],
        truth["Lon (deg)"][sampled],
        truth["Alt (km)"][sampled],
        strict=True,
    ):
        et = spicetime.adapt(np.datetime64(timestamp), "dt64", "et")
        position = sp.spkpos("-143013", et, "ITRF93", "NONE", "EARTH")[0]
        longitude, latitude, altitude = sp.recgeo(position, equatorial_radius, flattening)
        latitude_error.append(np.degrees(latitude) - ref_lat)
        longitude_error.append(np.degrees(longitude) - ref_lon)
        altitude_error.append(altitude - ref_alt)

    # The reference lat/lon are quoted to 3 decimal places, so agreement is bounded below by the
    # 0.001 deg quantum regardless of how good the ephemeris is. Observed residuals sit at half a
    # quantum in both components -- including latitude, which Earth-rotation error cannot touch --
    # so this is reference rounding rather than ephemeris error.
    assert np.abs(latitude_error).max() < 1e-3, np.abs(latitude_error).max()
    assert np.abs(longitude_error).max() < 1e-3, np.abs(longitude_error).max()
    # Altitude is quoted to six decimals, so it admits a far tighter bound.
    assert np.abs(altitude_error).max() < 5e-3, np.abs(altitude_error).max()


def test_frozen_kernels_geolocate_the_scan_over_libya4(frozen_kernel_manager):
    """Geolocating the frozen kernels puts the cross-track scan across the Libya-4 site.

    Validation provenance
    ---------------------
    Supersedes the Tier-1 ``test_geolocate_earth_target`` (LIBSDC-703). Same Libya-4 scenario and
    the same quality-flag bound, but it consumes pre-generated kernels instead of building nine of
    them per run, and it checks proximity to the actual site rather than a hand-tuned bounding box
    around a swath median.

    The end-to-end check: static offsets, spacecraft ephemeris and attitude, both mechanism CKs
    and the frame kernel compose into a ground track over the intended target. The tolerance is
    loose by design -- the assertion is "the scan crosses the site", not a pinned footprint,
    because near the limb the intersection is acutely sensitive to sub-arcminute pointing and a
    tight bound would be fragile. The exact mechanism geometry is pinned by the CK tests above.
    """
    times = pd.date_range(FIXTURE_START, FIXTURE_END, freq="10ms", inclusive="left")
    lla, _, quality_flags = spatial.compute_ellipsoid_intersection(
        spicetime.adapt(times, "iso"),
        sp.obj.Body("LIBERA_RAD", frame=True),
        give_geodetic_output=True,
        give_lat_lon_in_degrees=True,
    )

    # Most samples intersect the ellipsoid; the rest are the wide cross-track scan grazing the
    # limb, which is expected geometry rather than a failure. The 0.78 bound is carried over
    # unchanged from the Tier-1 validation, and the 60 s window reproduces it (0.7882 measured)
    # because limb grazing comes from the +/-72 deg sweep, not from the length of the window.
    good_fraction = (quality_flags == 0).sum() / len(quality_flags)
    assert good_fraction >= 0.78, good_fraction

    latitude = lla["lat"].to_numpy()
    longitude = lla["lon"].to_numpy()
    finite = np.isfinite(latitude) & np.isfinite(longitude)
    assert finite.any(), "No sample intersected the ellipsoid"

    site_lat, site_lon = np.deg2rad(LIBYA4_LAT_DEG), np.deg2rad(LIBYA4_LON_DEG)
    sample_lat, sample_lon = np.deg2rad(latitude[finite]), np.deg2rad(longitude[finite])
    haversine = (
        1 - np.cos(sample_lat - site_lat) + np.cos(site_lat) * np.cos(sample_lat) * (1 - np.cos(sample_lon - site_lon))
    ) / 2
    distance_km = 2 * constants.WGS84_SEMI_MAJOR_AXIS_KM * np.arcsin(np.sqrt(haversine))

    # The scan sweeps +/-72 deg across the site, so some sample lands very near it. The bound is
    # set by how coarsely the fast sweep samples the ground, not by pointing accuracy.
    assert distance_km.min() < 10.0, (
        f"Closest sample is {distance_km.min():.3f} km from Libya-4; the scan does not cross the site"
    )


def test_measured_misalignment_shifts_the_geolocated_footprint(
    generic_kernel_dir, isolated_kernel_cache, curryer_lsk, nominal_frame_kernel, short_tmp_path, test_data_path
):
    """The measured misalignment changes where the scan lands on the ground.

    Validation provenance
    ---------------------
    Descends from the Tier-1 misalignment A/B check (LIBSDC-806). It geolocates the same scan
    twice from one spacecraft state -- once with the measured axes and boresight, once with the
    ideal orthogonal gimbal -- and requires the two footprints to differ.

    The measured leg reuses the frozen fixture; only the nominal leg is built here, from the same
    source rows via the fixture generator's own frame builders, so the two configurations differ
    in geometry alone and not in sampling, window, or input data. Differencing within one run also
    cancels common-mode platform geometry, which is what keeps the check deterministic across
    msopck builds where an absolute footprint would not be.

    The *size* of the offset is validated against the engineering line-of-sight in
    ``test_los_alignment.py``, and that the CKs turn about the measured axes at all is pinned
    exactly by the mechanism-CK tests above. What this adds is that the effect survives the full
    chain through to latitude and longitude.
    """
    from libera_utils import kernel_maker
    from libera_utils.config import config
    from libera_utils.libera_spice import spice_utils
    from libera_utils.libera_spice.kernel_manager import KernelManager
    from tests.fixture_generation import generate_dynamic_kernels as fixture_gen

    kernel_dir = test_data_path / "dynamic_kernels"
    frozen = sorted(f for f in kernel_dir.iterdir() if f.is_file())

    times = pd.date_range(FIXTURE_START, FIXTURE_END, freq="20ms", inclusive="left")
    ugps_times = spicetime.adapt(times, "iso")

    def geolocate() -> pd.DataFrame:
        lla, _, _ = spatial.compute_ellipsoid_intersection(
            ugps_times,
            sp.obj.Body("LIBERA_RAD", frame=True),
            give_geodetic_output=True,
            give_lat_lon_in_degrees=True,
        )
        return lla

    km = KernelManager()
    km.load_libera_dynamic_kernels(frozen, needs_naif_kernels=True, needs_static_kernels=True)
    measured_lla = geolocate()

    # Nominal leg: same source rows, quaternions rebuilt about the ideal axes, and the
    # misalignment-free frame kernel swapped in for the production one.
    nominal_kernels = []
    for builder, field, axis, config_key in (
        (fixture_gen.azimuth_frame, kernel_maker.AZ_ENCODER_FIELD, NOMINAL_AZ_AXIS, "LIBERA_KERNEL_AZ_CK_CONFIG"),
        (fixture_gen.elevation_frame, kernel_maker.EL_ENCODER_FIELD, NOMINAL_EL_AXIS, "LIBERA_KERNEL_EL_CK_CONFIG"),
    ):
        frame, _ = builder()
        kernel_maker.apply_encoder_corrections(frame)
        quaternions = kernel_maker.mechanism_quaternions(frame[field].to_numpy(), axis)
        for name, column in zip(kernel_maker.MECHANISM_QUATERNION_COLUMNS[field], quaternions.T, strict=True):
            frame[name] = column
        nominal_kernels.append(spice_utils.make_kernel(config.get(config_key), short_tmp_path, input_data=frame))

    # Swap only what differs, rather than reloading the whole set: unload the measured mechanism
    # CKs and the production frame kernel, then furnish the nominal ones. The spacecraft ephemeris
    # and attitude stay exactly as furnished for the measured leg, so they cannot contribute to
    # the difference.
    for furnished in spice_utils.ls_kernels():
        if any(tag in Path(furnished.file_name).name for tag in ("AZROT-CK", "ELSCAN-CK")):
            sp.unload(furnished.file_name)
    sp.unload(str(config.get("LIBERA_KERNEL_FRAME")))

    sp.furnsh(str(nominal_frame_kernel))
    for nominal_kernel in nominal_kernels:
        sp.furnsh(str(nominal_kernel))
    nominal_lla = geolocate()

    measured_lat = measured_lla["lat"].to_numpy()
    measured_lon = measured_lla["lon"].to_numpy()
    nominal_lat = nominal_lla["lat"].to_numpy()
    nominal_lon = nominal_lla["lon"].to_numpy()
    comparable = (
        np.isfinite(measured_lat) & np.isfinite(measured_lon) & np.isfinite(nominal_lat) & np.isfinite(nominal_lon)
    )
    assert comparable.sum() > comparable.size // 2, comparable.mean()

    # The core statement: removing the misalignment collapses the two configurations to equality.
    assert not np.allclose(measured_lat[comparable], nominal_lat[comparable]) or not np.allclose(
        measured_lon[comparable], nominal_lon[comparable]
    )


def test_frozen_mechanism_ck_coverage_matches_the_documented_window(frozen_kernel_manager, test_data_path):
    """The frozen mechanism CKs cover exactly the window the generation script documents.

    Downstream repos pin their test epochs to this window, so a silent coverage change needs to
    fail here rather than as a confusing SPICE insufficient-data error somewhere else.
    """
    from libera_utils.config import config

    kernel_dir = test_data_path / "dynamic_kernels"
    with sp.ext.load_kernel(config.get("LIBERA_KERNEL_CLOCK")):
        for pattern, body in (("*AZROT-CK*.bc", "LIBERA_AZ"), ("*ELSCAN-CK*.bc", "LIBERA_EL")):
            (kernel_file,) = kernel_dir.glob(pattern)
            start, end = sp.ext.kernel_coverage(kernel_file, sp.obj.Body(body, frame=True), to_fmt="iso")
            assert start.startswith(FIXTURE_START), (body, start)
            assert end.startswith(FIXTURE_END), (body, end)
