#
# Copyright 2010-2020 Boxfuse GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# REFERENCE: https://flywaydb.org/documentation/configfiles

# URL Format for JDBC
# PostgreSQL        : jdbc:postgresql://<host>:<port>/<database>?<key1>=<value1>&<key2>=<value2>...
# flyway.url=jdbc:postgresql://localhost:5432/dev

# User to use to connect to the database. Flyway will prompt you to enter it if not specified, and if the JDBC
# connection is not using a password-less method of authentication.
flyway.user=libera_master

# Password to use to connect to the database. Flyway will prompt you to enter it if not specified, and if the JDBC
# connection is not using a password-less method of authentication.
# For development, we have no password set and HBA is set to trust but this needs to be here to prevent a prompt
# flyway.password={FLYWAY_PASSWORD}

# The default schema managed by Flyway. This schema name is case-sensitive. If not specified, but <i>flyway.schemas</i> is, Flyway uses the first schema
# in that list. If that is also not specified, Flyway uses the default schema for the database connection.
# Consequences:
# - This schema will be the one containing the schema history table.
# - This schema will be the default for the database connection (provided the database supports this concept).
flyway.defaultSchema=public

# Comma-separated list of schemas managed by Flyway. These schema names are case-sensitive. If not specified, Flyway uses
# the default schema for the database connection. If <i>flyway.defaultSchema</i> is not specified, then the first of
# this list also acts as default schema.
# Consequences:
# - Flyway will automatically attempt to create all these schemas, unless they already exist.
# - The schemas will be cleaned in the order of this list.
# - If Flyway created them, the schemas themselves will be dropped when cleaning.
flyway.schemas=public

# Comma-separated list of directories containing JDBC drivers and Java-based migrations.
# (default: <INSTALL-DIR>/jars)
# We leave this configured but blank to prevent flyway from looking for Java-based migrations
flyway.jarDirs=

# Whether to disable clean. (default: false)
# This is especially useful for production environments where running clean can be quite a career limiting move.
flyway.cleanDisabled=true

# Whether to validate migrations and callbacks whose scripts do not obey the correct naming convention. A failure can be
# useful to check that errors such as case sensitivity in migration prefixes have been corrected.
# false to continue normally, true to fail fast with an exception (default: false)
flyway.validateMigrationNaming=true

# Whether to group all pending migrations together in the same transaction when applying them
# (only recommended for databases with support for DDL transactions)

# This ensures that we never end up with a database in a broken state. All pending migrations either succeed or fail
# together. i.e. it prevents the situation where a future migration relies on a previous migration but there was
# a non-fatal mistake in the earlier migration such that V1 succeeds, V2 fails because there is a mistake in V1.
# With group=true, both migrations will be rolled back so we can simply fix V1 instead of creating a whole new
# migration and manually undoing the accidental damage from V1.
flyway.group=true