GRANT USAGE ON SCHEMA sdp TO processor_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA sdp GRANT SELECT, INSERT, UPDATE ON TABLES TO processor_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA sdp GRANT USAGE, SELECT ON SEQUENCES TO processor_role;

-- tester_role only exists in our local dockerized DB. This makes the migration compatible with the RDS
DO $$BEGIN
IF EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'tester_role')
THEN
    GRANT ALL ON SCHEMA sdp TO tester_role;
    ALTER DEFAULT PRIVILEGES IN SCHEMA sdp GRANT ALL PRIVILEGES ON TABLES TO tester_role;
    ALTER DEFAULT PRIVILEGES IN SCHEMA sdp GRANT USAGE, SELECT ON SEQUENCES TO tester_role;
END IF;
END$$;

GRANT USAGE ON SCHEMA sdp TO reader_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA sdp GRANT SELECT ON TABLES TO reader_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA sdp GRANT USAGE, SELECT ON SEQUENCES TO reader_role;